name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # MLIR build
  build-mlir:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake bootstrap 
      run: ./scripts/bootstrap-mlir.sh
    - name: make
      run: |
        cd build
        ninja
