name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # MLIR build
  build-mlir:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt and setup
      run: |
        sudo apt-get install -y ninja-build lld-9 clang++-9 clang-9
        sudo update-alternatives --install "/usr/bin/clang" "clang" "/usr/bin/clang-9" 10
        sudo update-alternatives --install "/usr/bin/clang++" "clang++" "/usr/bin/clang++-9" 10
        sudo update-alternatives --install "/usr/bin/ld.lld" "ld.lld" "/usr/bin/ld.lld-9" 10
        sudo update-alternatives --install "/usr/bin/lld" "lld" "/usr/bin/lld-9" 10
    - name: cmake bootstrap 
      run: ./scripts/bootstrap-mlir.sh
    - name: make
      run: |
        cd build
        ninja
