name: sync with upstream

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: sync
        run: |
          git remote add upstream https://github.com/llvm/llvm-project
          git fetch upstream
          git checkout master

          # TODO: Only push there is a change
          git pull upstream master && git push origin master
